sudo: false

language: node_js

node_js:
  - "6.1"
  - "6.0"
  - "5.11"
  - "5.10"
  - "5.9"
  - "5.8"
  - "5.7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"

addons:
  code_climate:
    repo_token: 8a41dd92ec7457de70130c4b7baecc0aa47d15c104346a47ae283ad6a9289507

before_script:
  - node sleep.js

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
